name: Backend CI

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install flake8 pytest django djangorestframework

      - name: Lint with flake8
        run: flake8 . || true

      - name: Run tests with pytest
        run: pytest --maxfail=1 --disable-warnings -q
